[package]
name = "chat-app"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio.workspace = true
actix-web.workspace = true
env_logger.workspace = true
log.workspace = true
serde.workspace = true
serde_yaml.workspace = true
